
# Configuration for training on the ShapeNetCore dataset

# [Data settings]
data_dir: "./data/ShapeNetCore.v2"  # Replace with the actual path to your dataset

# [Training settings]
ckpt_path: null  # Path to checkpoint if resuming training, otherwise null
gpu: 0  # GPU ID
degree: 3 # Degree of spherical harmonics
num_classes: 55 # ShapeNetCore dataset classnames

# [Hyperparameter settings]
lr: 0.001 #Optimizer Learning Rate
gamma: 0.98 #Scheduler Gamma Value
max_epochs: 300
batch_size: 64